# SPDX-FileCopyrightText: 2023 The Pion community <https://pion.ly>
# SPDX-License-Identifier: MIT

FROM golang:1.23

RUN go install gitlab.cubicmedia.cloud/cubic-ai/CA/webrtc/v4/examples/pion-to-pion/answer@latest

CMD ["answer"]

EXPOSE 50000
